### ISSUE TITLE
cant find values from config file

### ISSUE THREAD

**Issue by obinschoudhary** [5agado/recurrent-neural-networks-intro#1]
Is model_id and model parameters coming from models.ini? Cant see models.ini config file.

**Comment by 5agado** [comment]
*models.ini* should be an external file which path is specified in the *config.ini* file present in the project.
Is external because it greatly depends on the way you do model management. For my case the content is on the like of the following

```
[bible_tf]
config_yaml_path:/models/tf_rnn_bible/config.yaml
index_to_word_path:/models/tf_rnn_bible/bible_idxs_vocab_8002.txt
host:127.0.0.1
port:9000
type:continuous

[songdata_tf]
config_yaml_path:/models/songdata/config.yaml
index_to_word_path:/models/songdata/songdata_idxs_vocab_8002.txt
host:127.0.0.1
port:9000
type:continuous

[standard_config]
sent_max_len:30 
temperature:0.9
use_embeddings:true
```

*host* and *port* are about the tensorflow serving server.

And the *config.yaml* is itself related to the tensorflow model info. Something like:

```
basicModelInfo:
  name: rnn_darwin
  version: 1
  signature_name: predict
default_signature:
  inputs:
    - name: inputs
      type: float32
      shape: (1,20,)
  outputs:
    outputs:
      type: float32
      shape: (1,)
```

As you can see there is some external configuration and work required. I didn't optimize the code and comments for direct use, but more to play around. Still, if you have any more questions, feel free.
